apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::435838053719:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12WQR1IMXVVL5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::435838053719:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-20T18:55:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8256"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dab78761-2436-433a-8e12-3ea2b14dd9a3